server:
    port: 4000

logging:
  level:
    ROOT: DEBUG
    io.github.jhipster: DEBUG
    ar.incluit.fintech.anses.servidor: DEBUG

spring:
  batch:
    job:
      enabled: false

backoffice:
  url: local:4200/#/auth/login/check
ws:
  url: localhost:9090/ws/entrevistas.wsdl