server:
    port: 4000

logging:
    level:
          or:
            springframework:
                            ws: TRACE

spring:
  batch:
    job:
      enabled: false

backoffice:
  url: http://localhost:4200/#/auth/login/check
ws:
  url: http://10.201.4.214:9090/ws/entrevistas.wsdl