server:
    port: 4000

logging:
    level:
          or:
            springframework:
                            ws: TRACE

spring:
  batch:
    job:
      enabled: false

backoffice:
  url: local:4200/#/auth/login/check
ws:
  url: localhost:9090/ws/entrevistas.wsdl